# winget-dsc pipeline to publish module artifacts
name: '$(Build.DefinitionName)-$(Build.DefinitionVersion)-$(Date:yyyyMMdd)-$(Rev:r)'

trigger: none

parameters: # parameters are shown up in ADO UI in a build queue time

- name: 'Microsoft.Windows.Developer'
  displayName: 'Publish Microsoft.Windows.Developer to PSGallery'
  type: boolean
  default: false

resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows
    customBuildTags:
      - ES365AIMigrationTooling
    settings:
      skipBuildTagsForGitHubPullRequests: true

    stages:
      - stage: Manual Approval
        displayName: Manual Approval
        dependsOn: []
        jobs:
        - ${{ if eq(parameters.Microsoft.Windows.Developer, false) }}:
          - template: /azure-pipelines/templates/manual-trigger.yml@self
            parameters:
              publishTarget: Microsoft.Windows.Developer PSGallery
        - template: /azure-pipelines/templates/jobs/publish/store.yml@self
          parameters:
            runImmediately: ${{ parameters.msstore }}
      - stage: Publish pipeline artifact
        jobs:
        - job: Publish pipeline artifact
          displayName: 'Publish Microsoft.Windows.Developer'
          templateContext:
            outputs:
              - output: pipelineArtifact
                displayName: Publish ${{ parameters.buildName }}
                targetPath: $(Build.SourcesDirectory)\resources\Microsoft.Windows.Developer\
                artifactName: Microsoft.Windows.Developer
